FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y mariadb-server
RUN mkdir "/run/mysqld"
EXPOSE 3306

LABEL version="1.0"
LABEL description="MariaDB Server"

VOLUME /var/lib/mysql

CMD ["mysqld", "--user=root"]
