FROM ubuntu:22.04


RUN apt-get update


ENV TZ Europe/Paris
ENV DEBIAN_FRONTEND noninteractive


RUN apt-get install -y wordpress mariadb-client nano


RUN ln -s /usr/share/wordpress/ /var/www/wordpress

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

COPY config-localhost.php /etc/wordpress/config-localhost.php

EXPOSE 80


CMD ["apachectl", "-D", "FOREGROUND"]