version: '3'
services:
  db:
    image: db:latest
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
  wp:
    image: wp:latest
    depends_on:
      - db
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./data/wp-content:/var/www/html/wp-content
